name: transformers_basic_deploy_env
channels:
  - defaults
dependencies:
  - python=3.7.11
  - pip=20.0
  - pip:
    - transformers==4.21.2
    - fire==0.4.0
    - torch==1.12.1
    - azureml-defaults
